name: REPortfolio-iOS
options:
  bundleIdPrefix: com.re
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_BUNDLE_IDENTIFIER: com.re.portfolio.ios
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_FILE: ""
    GENERATE_INFOPLIST_FILE: "YES"
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: "YES"
    INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"

targets:
  REPortfolio-iOS:
    type: application
    platform: iOS
    sources:
      - path: REPortfolioApp.swift
      - path: DesignSystem
      - path: Data
      - path: Utils
      - path: UI
    settings:
      base:
        PRODUCT_NAME: REPortfolio
