import SwiftUI

// AUTO-GENERATED by design-system/generate.js — DO NOT EDIT MANUALLY
// Source of truth: design-system/tokens.json
// To update: edit tokens.json → run node generate.js → copy this file

extension Color {
    // Brand
    static let brandPrimary          = Color(hex: "0069E0")
    static let brandText             = Color(hex: "0056B8")

    // Insight
    static let insightBaseUltralight = Color(hex: "F7F0FF")
    static let insightBaseLight      = Color(hex: "EAE6FE")
    static let purpleLight           = Color(hex: "E6E0FF")
    static let insightAccentBg       = Color(hex: "E0EFFF")
    static let insightSparkle        = Color(hex: "7B4EFF")

    // Surfaces
    static let surfaceWhite          = Color(hex: "FFFFFF")
    static let surfaceAccentBase     = Color(hex: "FBF6EF")
    static let surfaceLowContrast    = Color.black.opacity(0.05)

    // Text
    static let textPrimary           = Color.black.opacity(0.88)
    static let textSecondary         = Color.black.opacity(0.62)
    static let textDisabled          = Color.black.opacity(0.4)
    static let textGreen             = Color(hex: "218362")

    // Borders & Shadows
    static let borderSubtle          = Color.black.opacity(0.1)
    static let shadowNeutralLow      = Color.black.opacity(0.06)

    // Onboarding / Form
    static let successGreen          = Color(hex: "218362")
    static let errorRed              = Color(hex: "D32F2F")
    static let formFieldBg           = Color(hex: "F4F5F7")
    static let formFieldBorder       = Color(hex: "EBECF0")
    static let successScreenBg       = Color(hex: "E8F5E9")
}

// Hex initialiser — allows Color(hex: "0069E0") from any file in this module
extension Color {
    init(hex: String) {
        let scanner = Scanner(string: hex)
        var rgb: UInt64 = 0
        scanner.scanHexInt64(&rgb)
        let r = Double((rgb >> 16) & 0xFF) / 255.0
        let g = Double((rgb >>  8) & 0xFF) / 255.0
        let b = Double( rgb        & 0xFF) / 255.0
        self.init(red: r, green: g, blue: b)
    }
}