import Foundation

// AUTO-GENERATED by design-system/generate.js — DO NOT EDIT MANUALLY
// Source of truth: design-system/tokens.json

enum Tokens {
    enum Spacing {
        static let zero: CGFloat = 0
        static let xs: CGFloat = 2
        static let s: CGFloat = 4
        static let m: CGFloat = 6
        static let l: CGFloat = 8
        static let xl: CGFloat = 12
        static let xxl: CGFloat = 16
        static let xxxl: CGFloat = 20
        static let xxxxl: CGFloat = 24
        static let widgetsXs: CGFloat = 28
        static let widgetsM: CGFloat = 36
    }

    enum Radius {
        static let sm: CGFloat = 12  // local demand card
        static let element: CGFloat = 16
        static let card: CGFloat = 20
        static let full: CGFloat = 1000  // pill shape
    }

    enum Elevation {
        static let low: CGFloat = 2
        static let med: CGFloat = 4
        static let cardShadow: CGFloat = 12  // Figma blur 12px rgba(0,0,0,0.06)
    }
}

// Convenience typealiases for call-site brevity
// Usage: Spacing.xxl, Radius.card, Elevation.cardShadow
typealias Spacing   = Tokens.Spacing
typealias Radius    = Tokens.Radius
typealias Elevation = Tokens.Elevation