import SwiftUI

// AUTO-GENERATED by design-system/generate.js — DO NOT EDIT MANUALLY
// Source of truth: design-system/tokens.json

enum Typography {
    // Est. ₹2.15 Cr hero — Black
    static let priceHero = Font.system(size: 44, weight: .black)
    // Apply with: .lineSpacing(...) or .tracking(-0.88) — tracking: -0.88
    
    // Est. label beside price — Bold
    static let priceLabel = Font.system(size: 20, weight: .bold)
    // Apply with: .lineSpacing(...) or .tracking(-0.4) — lineHeight: 28, tracking: -0.4
    
    // Cr suffix — Bold (same as priceLabel)
    static let priceSuffix = Font.system(size: 20, weight: .bold)
    // Apply with: .lineSpacing(...) or .tracking(-0.4) — lineHeight: 28, tracking: -0.4
    
    // ₹85-98 L price hero — Black
    static let displaySmall = Font.system(size: 36, weight: .black)
    // Apply with: .lineSpacing(...) or .tracking(-0.72) — lineHeight: 48, tracking: -0.72
    
    // Section overline — SemiBold, wide tracking
    static let overline = Font.system(size: 11, weight: .semibold)
    // Apply with: .lineSpacing(...) or .tracking(0.88) — lineHeight: 16, tracking: 0.88
    
    // Card title — Bold
    static let titleSmall = Font.system(size: 16, weight: .bold)
    // Apply with: .lineSpacing(...) or .tracking(-0.32) — lineHeight: 24, tracking: -0.32
    
    // Stats value — SemiBold
    static let bodyLarge = Font.system(size: 16, weight: .semibold)
    // Apply with: .lineSpacing(...) or .tracking(-0.128) — lineHeight: 24, tracking: -0.128
    
    // Button label — SemiBold
    static let bodyMedium = Font.system(size: 14, weight: .semibold)
    // Apply with: .lineSpacing(...) or .tracking(-0.112) — lineHeight: 20, tracking: -0.112
    
    // Stats sub-label — Medium
    static let bodySmall = Font.system(size: 12, weight: .medium)
    // Apply with: .lineSpacing(...) or .tracking(-0.096) — lineHeight: 16, tracking: -0.096
    
    // Insight text — Regular
    static let bodySmallThin = Font.system(size: 12, weight: .regular)
    // Apply with: .lineSpacing(...) or .tracking(-0.096) — lineHeight: 16, tracking: -0.096
    
    // Badge — SemiBold
    static let captionMed = Font.system(size: 11, weight: .semibold)
    // Apply with: .lineSpacing(...) or .tracking(0) — lineHeight: 16, tracking: 0
    
    // Disclaimer — Regular
    static let bodyMediumThin = Font.system(size: 14, weight: .regular)
    // Apply with: .lineSpacing(...) or .tracking(-0.112) — lineHeight: 20, tracking: -0.112
    
}
    
// Convenience modifier — applies font + tracking + color in one call
// Usage: Text("hello").textStyle(Typography.bodyLarge)
extension View {
    func textStyle(_ font: Font, tracking: CGFloat = 0, color: Color = .textPrimary) -> some View {
        self
            .font(font)
            .tracking(tracking)
            .foregroundColor(color)
    }
}